### ISSUE TITLE
Support modern fastify 3.x

### ISSUE THREAD

**Issue by igorshmukler** [MetCoder95/fastify-get-head#4]
Currently, do the `fastify: '>=3.8 <= 3.9',` statement modern fastify, which has the version number above 3.9 is not supported.

**Describe the solution you'd like**
I want the modern fastify 3.x supported by changing the line to `fastify: '>=3.8 < 4',`

**Describe alternatives you've considered**

**Additional context**
Currently, we get the below:
```
  name: 'FastifyError',
  code: 'FST_ERR_PLUGIN_VERSION_MISMATCH',
  message: "fastify-plugin: fastify-get-head - expected '>=3.8 <= 3.9' fastify version, '3.20.2' is installed",
  statusCode: 500
```

**Comment by MetCoder95** [comment]
Hi @igorshmukler , thanks a lot for opening this issue!
This is made in this way on purpose as has the merely objective of support fastify versions prior to `v3.9`, as starting at this version `fastify` now includes the flag `exposeHeadRoutes` which applies this specific behavior. See the [following docs](https://www.fastify.io/docs/latest/Server/#exposeheadroutes). On `v4` of `fastify`, this behavior will be enabled by default.

For instance this plugin is not made to work with greater versions of `fastify` 🙂

**Comment by igorshmukler** [comment]
@MetCoder95 I thought that HEAD to GET was set aside until 4.x. got it, now. thank you for the plugin and addressing my issue.
