### ISSUE TITLE
fastify 4.0 support

### ISSUE THREAD

**Issue by BrycensRanch** [metcoder95/fastify-get-head#5]
self explanatory, the repo hasnt been updated in years lol

**Comment by metcoder95** [comment]
👋 
Yeah, well haha
The thing is that Fastify@4 onwards already provides this functionality out-of-the-box.
This plugin remains open for those services for which migration is not possible or not an easy thing but wants to use this feature.

Are you trying to use the plugin with Fastify@4?

**Comment by BrycensRanch** [comment]
yes, I didn't know fastify now implements it. Do you have any examples? Thanks for your fast response!

**Comment by metcoder95** [comment]
Sure thing!

There's no need to do something fancy, is enough to either use the [`exposeHeadRoutes`](https://www.fastify.io/docs/latest/Reference/Server/#exposeheadroutes) global flag or enable it per route using [`exposeHeadRoute`](https://www.fastify.io/docs/latest/Reference/Routes/#routes-options) 👍 

I'll close it now, but happy to give you any support in that regard
